// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// compute_cors_cpp
Eigen::MatrixXd compute_cors_cpp(const Eigen::Map<Eigen::MatrixXd>& X, const Eigen::Map<Eigen::VectorXd>& Y);
RcppExport SEXP _intscreen_compute_cors_cpp(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_cors_cpp(X, Y));
    return rcpp_result_gen;
END_RCPP
}
// compute_cors_mod_cpp
Eigen::MatrixXd compute_cors_mod_cpp(const Eigen::Map<Eigen::MatrixXd>& X, const Eigen::Map<Eigen::VectorXd>& Y, const Eigen::Map<Eigen::VectorXd>& mod);
RcppExport SEXP _intscreen_compute_cors_mod_cpp(SEXP XSEXP, SEXP YSEXP, SEXP modSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type mod(modSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_cors_mod_cpp(X, Y, mod));
    return rcpp_result_gen;
END_RCPP
}
// construct_ints_cpp
Eigen::MatrixXd construct_ints_cpp(const Eigen::Map<Eigen::MatrixXd>& X, const Eigen::Map<Eigen::MatrixXi>& whichints);
RcppExport SEXP _intscreen_construct_ints_cpp(SEXP XSEXP, SEXP whichintsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXi>& >::type whichints(whichintsSEXP);
    rcpp_result_gen = Rcpp::wrap(construct_ints_cpp(X, whichints));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_intscreen_compute_cors_cpp", (DL_FUNC) &_intscreen_compute_cors_cpp, 2},
    {"_intscreen_compute_cors_mod_cpp", (DL_FUNC) &_intscreen_compute_cors_mod_cpp, 3},
    {"_intscreen_construct_ints_cpp", (DL_FUNC) &_intscreen_construct_ints_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_intscreen(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
